### ISSUE TITLE
Uren registratie template

### ISSUE THREAD

**Issue by ioncap** [TijmenUU/keepi-vue#17]
Het begint echt een pracht tool te worden zeg, PHOOAAHH! Wat het nog mooier zou maken, is een template functie. 
Waarmee je als het waren een week opzet/standaard uren aantal in 1 klik kan vullen voor de hele week, voor de verschillende categorieën.

**Comment by tijmenpitcrew** [comment]
Zou het voldoende zijn als je maar één "template" per project hebt? Of wil je er meerdere kunnen hebben per project?

Met per project heb ik het dus over de rijen in het invoerscherm, je zou bijvoorbeeld rechts van die rij een optionele sjabloon knop kunnen hebben.

**Comment by TijmenUU** [comment]
@ioncap Het makkelijkste voor nu was om weken te kopiëren in zijn geheel. Hier zijn twee nieuwe knopjes geïntroduceerd (zie afbeelding). Je kan hiermee navigeren naar een willekeurige week, kopieren en dan plakken over iedere andere week. Vergeet niet op opslaan te drukken als je de geplakte waarden wilt behouden :wink: 

![image](https://github.com/TijmenUU/keepi-vue/assets/8997518/a4dfb8c7-a6be-4e0f-ae9d-45609e6aec17)
