### ISSUE TITLE
categorie opslaan/toevoegen

### ISSUE THREAD

**Issue by ioncap** [TijmenUU/keepi-vue#18]
Zodra ik een categorie wil toevoegen, en vul alle benodigde velden, en druk op opslaan in plaats van toevoegen, wordt er niets opgeslagen.
Logisch hoor ik je denken, want daar heb je de f*kn knop toevoegen voor, flapdrol!
En daar heb je helemaal gelijk in, toch is het handig om de velden toe te voegen zodra er op opslaan wordt gedrukt, indien de velden gevuld zijn met correcte data uiteraard.

Is het mogelijk een dergelijke stap/controle uit te voeren zodra er op opslaan gedrukt word vanaf de categorie toevoegen pagina?

**Comment by tijmenpitcrew** [comment]
Ja, wellicht dat de opslaan knop moet blokkeren als er geen wijzigingen zijn. Als we het toevoegen nou naar een modal verplaatsen dan moet je die eerst bewust sluiten voordat je iets anders kan, voorkomt waarschijnlijk ook weer ellende.

**Comment by TijmenUU** [comment]
Opgelost in het categorieen scherm dat:
- je niet een regel kan toevoegen waar nog niet alles van is ingevuld
- je niet kan opslaan als er nog openstaande wijzigingen zijn in de "toe te voegen regel"

**Comment by tijmenpitcrew** [comment]
@ioncap Ik heb in https://github.com/TijmenUU/keepi-vue/pull/29 nog wat meer sanity checks toegevoegd. Er komt nu een pop-up als je weg wilt navigeren en er nog niet opgeslagen wijzigingen zijn.

Validaties van de velden zelf mist nog (hij zegt niet wat er fout is als je gekke dingen doet). Dat komt hopelijk nog een andere keer :crossed_fingers:
