### ISSUE TITLE
Al geboekte tijd weergeven

### ISSUE THREAD

**Issue by MikePitCrew** [TijmenUU/keepi-vue#19]
De UI van Noko gebruik ik nog voor het opvoeren van specifieke afspraken. Deze tijd zie ik echter niet terug in het overzicht van Keepi(?)

Wellicht een idee om een rij met de al geboekte (overige) uren te weergeven? Of als alternatief een manier om deze specifieke afspraken in te kunnen dienen. Dat zou dan lijken op de UI van Noko.

**Comment by TijmenUU** [comment]
Het ondersteunen van specifieke afspraken gaat helaas teveel tegen de opzet van de app in. Dit zal het voorlopig niet kunnen doen.

Het in kunnen zien van tijd die niet aan een categorie is gebonden is wel meer in lijn met de app, maar ik moet wel redelijk wat verbouwen om dat in de matrix te krijgen. Als ik tijd is ga ik daar eens naar kijken :+1:

**Comment by TijmenUU** [comment]
Ik heb het toegevoegd in https://github.com/TijmenUU/keepi-vue/pull/27 . Voorbeeldje: 
![image](https://github.com/user-attachments/assets/e2beb334-756f-49e1-a33c-619c14bf22d5)

**Comment by TijmenUU** [comment]
Woeps, ik was daar de samenvattingen vergeten ook bij te werken, gefikst in https://github.com/TijmenUU/keepi-vue/pull/28: 
![image](https://github.com/user-attachments/assets/3f548452-b8e8-4abd-9882-96c039e5f54c)
