### ISSUE TITLE
Fracties toestaan

### ISSUE THREAD

**Issue by GeertenPitcrew** [TijmenUU/keepi-vue#21]
Momenteel werkt "3:30" wel, maar "3.5" niet. Het zou chill zijn als hij fracties begreep.

![image](https://github.com/TijmenUU/keepi-vue/assets/155436077/0f49cf24-33bb-4bbe-90ee-7692ac29364c)

**Comment by TijmenUU** [comment]
Oh boy, nog een input manier. Ik denk dat het op zich nog wel kan, maar misschien begint het dan ook tijd te worden om dit user instelbaar te maken. In principe is de notatie `1u2m` (1 uur en 2 minuten) de enige "volledig" ondersteunde manier. De colon notatie `1:02` werkt voor invoer maar wordt opnieuw geformatteerd als `1u2m` na het opslaan.

Om de boel intuïtief  te houden voor de gebruiker zou ik zeggen dat er een instellingen pagina komt, waar dan ook het token instelbaar is. Hier kan de gebruiker het te gebruiken format kiezen en dat wordt dan ook alleen ondersteund.

Zie jij dat ook zo voor je? Een alternatief is dat whatever notatie je als laatst gebruikt automatisch wordt toegepast.

**Comment by GeertenPitcrew** [comment]
Wat ook prima zou zijn is als 4.5 _niet_ werkt, maar er dan op enige manier wordt aangegeven wat je wel moet doen. (In dat geval zou ik gewoon alleen integers en 1u2m toestaan, mogelijk 1u30 ook..) Momenteel doet ie het gewoon niet zonder validatiefouten.

**Comment by TijmenUU** [comment]
Als het achterliggende probleem het gebrek aan transparante validatie is dan ja, dat heeft wat meer voeten in de aarde. Er zal iets als VeeValidatie, Vorms of andere validatie framework nodig zijn. Zal eens kijken welke met het minste gedoe te integreren is.

**Comment by TijmenUU** [comment]
Ik heb een minimale vorm van validatie toegevoegd waarmee het duidelijk is waarom iets niet werkt in de input matrix (weekoverzicht). Er mist alleen nog informatievoorziening over wat dan wel mag.

Mocht je alsnog rationale getallen willen kunnen invoeren open dan een nieuw issue :+1: .
