### ISSUE TITLE
"Vandaag" highlighten

### ISSUE THREAD

**Issue by GeertenPitcrew** [TijmenUU/keepi-vue#25]
Het zou chill zijn als de huidige dag net even anders weergegeven wordt! Dat is handig want dan vul ik niet meer perongeluk de verkeerde dagen / weken in. 😋

**Comment by TijmenUU** [comment]
Ik heb een subtiele hint toegevoegd in de vorm van een asterisk achter "vandaag" in de matrix input (https://github.com/TijmenUU/keepi-vue/pull/26). Is dit bruikbaar?

Ik heb wat geëxperimenteerd met achtergrond kleurtjes, omlijningen, enzovoorts maar vond het allemaal wat druk ervan worden.

Voorbeeldje waar woensdag vandaag is:
![image](https://github.com/user-attachments/assets/4d3a6b66-0023-4ae7-acf3-69549b23be25)
