### ISSUE TITLE
Invoer veld navigatie

### ISSUE THREAD

**Issue by ioncap** [TijmenUU/keepi-vue#6]
Als gebruiker wil ik middels een logische toetseninvoer de tekstinvoer kunnen wijzigen in het log scherm.
Bijvoorbeeld: bij gebruik van meerdere categorieën is het logischer om bij een tab-toets wijziging eerst alle categorieën van de huidige datum (of geselecteerde datum) na te lopen voordat de invoer op een volgende dag gezet wordt.

**Comment by TijmenUU** [comment]
@ioncap Met de laatste versie kan je nu met de pijltjes toetsen zelf navigeren. Hopelijk is het zo logischer voor je 😉

De tab volgorde blijft van links naar rechts, van boven naar onderen.
